### ISSUE TITLE
Cucumber + Jira integration ticket status workflow update

### ISSUE THREAD

**Issue by grzegorzmlynarczyk** [serenity-bdd/serenity-jira#89]
Hi,

I saw a similar ticket, but it's dead since almost 2 years, so I'm creating a new one.
I've got a problem with two way integration with Jira. I am able to pull requirements, stories and tickets from jira to my reports, and to produce comments under those tickets if necessary. However, the status of the ticket is never updated in Jira.

I'm attaching following files for clarity (all links and usernames had to be erased):
[log.txt](https://github.com/serenity-bdd/serenity-jira/files/2262867/log.txt)
[pom.txt](https://github.com/serenity-bdd/serenity-jira/files/2262868/pom.txt)
[serenityproperties.txt](https://github.com/serenity-bdd/serenity-jira/files/2262869/serenityproperties.txt)

Here's my workflow:

```
when 'OPEN', {
    'success' should: 'Resolve Issuexx'
}

when 'REOPENED', {
    'success' should: 'Resolve Issue'
}

when 'RESOLVED', {
    'failure' should: 'Reopen Issue'
}

when 'IN PROGRESS', {
    'success' should: ['Stop Progress','Resolve Issue']
}

when 'CLOSED', {
    'failure' should: 'Reopen Issue'
}
```

I've already tried sticking to the default plugin workflow, changing the cases of the statuses, and also using thucydides properties - nothing seems to work.

**Comment by cliviu** [comment]
Hi, can you please post the pom.xml, serenity.properties and the log file of the test execution ?

**Comment by cliviu** [comment]
Hmm, do you have  

> Resolve Issuexx

 ?

**Comment by cliviu** [comment]
please set the property **serenity.public.url* , let me know if it works

**Comment by grzegorzmlynarczyk** [comment]
Hi,

> Hmm, do you have
> 
> Resolve Issuexx
> 
> ?

Yes, sorry - it was a typo, still not working. 

> please set the property serenity.public.url , let me know if it works

No changes.

**Comment by cliviu** [comment]
Hmm, can you please post the log after setting serenity.public.url to a non empty value ?

**Comment by grzegorzmlynarczyk** [comment]
Fixed an issue by adding 

`serenity.test.root=net.thucydides.showcase.cucumber.junit`

to serenity.properties. I have no idea what it does, but I saw it in couple of projects. Any clarity on that property? I'm curious, because it's not in the documentation.

**Comment by cliviu** [comment]
Did setting the serenity.public.url helped ?

**Comment by cliviu** [comment]
you find [here ](http://thucydides.info/docs/serenity-staging/) the documentation

serenity.test.root

    The root package for the tests in a given project. 
If provided, Serenity will use this as the root package when determining the capabilities associated with a test. 
If you are using the File System Requirements provider, Thucydides will expect this directory structure to exist at the top of the requirements tree.
 If you want to exclude packages in a requirements definition and start at a lower level in the hierarchy, use the serenity.requirement.exclusions property.

This is also used by the PackageAnnotationBasedTagProvider to know where to look for annotated requirements.
here you can also find an explanation https://dzone.com/articles/configuring-different-output-directories-with-sere

The serenity.test.root property is also important if you are writing your tests in JUnit because this tells Serenity what package root to use as a starting point for the requirements reporting. The package tree underneath this package will become the requirements tree in the reports.

try to play a bit with the property to get a feeling how the report is changing
https://dzone.com/articles/configuring-different-output-directories-with-sere
